'use client';
import {useEffect,useMemo,useState,type ButtonHTMLAttributes} from 'react';
import {ArrowLeft,ArrowRight,Check,Clipboard,ExternalLink,ShieldCheck,Sparkles} from 'lucide-react';
import {careCases} from '@/lib/cases';

type Answers=Record<string,string>;
type Rating={criterion:string;rating:'Strong'|'Developing'|'Revisit';strength:string;improvement:string};
type Feedback={ratings:Rating[];followUpQuestions:string[];overallNote:string};
const questions=[
 ['initial','Initial professional judgment','Before using CARE, what do you initially think the social worker or organization should do, and why?'],
 ['context','Context','What details about the people, setting, access conditions, power differences, professional obligations, and available alternatives should shape this decision?'],
 ['authority','Authority','What is the technology being allowed to do? Who selected or controls it? Who can override it, and who remains accountable for the final decision?'],
 ['risk','Risk and reversibility','What could happen if the technology is wrong, fails, excludes someone, or is used beyond its proper role? Who could be harmed? Could the decision be reversed without significant harm?'],
 ['engagement','Engagement','Which clients, communities, practitioners, or other affected people should participate? How and when should they influence design, testing, explanation, correction, and review?'],
 ['design','Design safeguard','What specific design or workflow safeguard is needed?'],
 ['oversight','Human oversight','What must a person review, when must that review occur, and what authority must the reviewer have?'],
 ['stop','Stop condition','What result or event should stop or redesign the technology?'],
 ['fallback','Safe fallback','What safe alternative remains available if the technology fails or causes harm?'],
] as const;
const stages=['Select','Analyze','Review','Revise','Submit'];

export default function Home(){
 const[stage,setStage]=useState(0),[moduleNumber,setModuleNumber]=useState(1),[questionIndex,setQuestionIndex]=useState(0);
 const[privacy,setPrivacy]=useState(false),[loading,setLoading]=useState(false),[copied,setCopied]=useState(false);
 const[answers,setAnswers]=useState<Answers>({}),[revised,setRevised]=useState<Answers>({}),[followUps,setFollowUps]=useState<Answers>({});
 const[feedback,setFeedback]=useState<Feedback|null>(null),[finalJudgment,setFinalJudgment]=useState(''),[changed,setChanged]=useState(''),[error,setError]=useState('');
 const item=careCases[moduleNumber-1],q=questions[questionIndex];
 const value=(key:string)=>revised[key]?.trim()||answers[key]?.trim()||'';
 const finalRecord=useMemo(()=>feedback?`FINAL CARE PRACTICE RECORD\n\nModule and case:\nModule ${item.module} — ${item.title}\n\nInitial professional judgment:\n${answers.initial||''}\n\nContext:\n${value('context')}\n\nAuthority:\n${value('authority')}\n\nRisk and reversibility:\n${value('risk')}\n\nEngagement:\n${value('engagement')}\n\nSafeguards and safe fallback:\nDesign safeguard: ${value('design')}\nHuman oversight: ${value('oversight')}\nStop condition: ${value('stop')}\nSafe fallback: ${value('fallback')}\n\nFinal professional judgment:\n${finalJudgment}\n\nWhat changed after feedback:\n${changed}\n\nRubric feedback:\n${feedback.ratings.map(r=>`${r.criterion} — ${r.rating}: ${r.improvement}`).join('\n')}`:'',[feedback,answers,revised,finalJudgment,changed,item]);
 useEffect(()=>{
  const modelContext=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!modelContext?.registerTool)return;
  const lifecycle=new AbortController();
  void Promise.resolve(modelContext.registerTool({name:'start_care_module',title:'Start a CARE module',description:'Select a fictional CARE case module and display its privacy confirmation step.',inputSchema:{type:'object',properties:{module:{type:'integer',minimum:1,maximum:12}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const module=Number((input as {module?:unknown})?.module);if(!Number.isInteger(module)||module<1||module>12)throw new Error('Module must be an integer from 1 through 12.');setModuleNumber(module);setStage(0);setPrivacy(false);setQuestionIndex(0);return {module,status:'selected',next:'Confirm the fictional-information privacy requirement in the visible app.'};}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[]);
 async function getFeedback(){setLoading(true);setError('');try{const res=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:moduleNumber,answers})});const data=await res.json();if(!res.ok)throw new Error(data.error);setFeedback(data);setStage(2)}catch(e){setError(e instanceof Error?e.message:'Feedback could not be generated.')}finally{setLoading(false)}}
 function reset(){setStage(0);setQuestionIndex(0);setPrivacy(false);setAnswers({});setRevised({});setFollowUps({});setFeedback(null);setFinalJudgment('');setChanged('');setCopied(false);setError('')}
 return <main className="min-h-screen bg-[#f6f4f1] text-[#202022]">
  <header className="border-b-4 border-[#8b0015] bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8b0015]">Technology in Social Work Practice</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">CARE Practice Coach</h1></div><ShieldCheck className="h-9 w-9 text-[#8b0015]" aria-hidden="true"/></div></header>
  <div className="mx-auto max-w-5xl px-5 py-7 sm:px-8">
   <nav aria-label="Activity progress" className="mb-7 grid grid-cols-5 gap-1">{stages.map((s,i)=><div key={s} className={`rounded-md px-2 py-2 text-center text-xs font-bold sm:text-sm ${i===stage?'bg-[#8b0015] text-white':i<stage?'bg-[#222] text-white':'bg-white text-stone-500'}`}>{i<stage?<Check className="mx-auto h-4 w-4 sm:hidden"/>:<span className="sm:hidden">{i+1}</span>}<span className="hidden sm:inline">{s}</span></div>)}</nav>
   <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-8">
    {stage===0&&<><Step n="1"/><h2 className="title">Choose your module</h2><p className="intro">The coach will guide you through one fictional case. Your professional judgment remains your own.</p><label className="label" htmlFor="module">Module and case</label><select id="module" value={moduleNumber} onChange={e=>setModuleNumber(Number(e.target.value))} className="field">{careCases.map(c=><option key={c.module} value={c.module}>Module {c.module} — {c.title}</option>)}</select><div className="mt-6 rounded-xl bg-[#f4e9ec] p-4"><p className="font-bold text-[#710012]">Privacy requirement</p><p className="mt-1 text-sm">Use only the fictional case. Do not enter real client, patient, agency, field-placement, health, contact, or identifying information.</p><label className="mt-4 flex items-start gap-3"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} className="mt-1 h-5 w-5 accent-[#8b0015]"/><span className="text-sm font-semibold">I understand and will use only fictional information.</span></label></div><Primary disabled={!privacy} onClick={()=>setStage(1)}>Begin CARE analysis <ArrowRight className="h-4 w-4"/></Primary></>}
    {stage===1&&<><p className="eyebrow">MODULE {item.module} · {item.focus}</p><h2 className="title">{item.title}</h2><div className="mt-5 rounded-xl border-l-4 border-[#8b0015] bg-stone-50 p-5"><p>{item.scenario}</p><p className="mt-4 font-bold">Decision point</p><p className="mt-1">{item.decision}</p></div><div className="mt-7 flex flex-wrap justify-between gap-2"><p className="eyebrow">QUESTION {questionIndex+1} OF {questions.length}</p><p className="text-sm text-stone-500">One or two thoughtful sentences is enough.</p></div><h3 className="mt-2 text-xl font-bold">{q[1]}</h3><label htmlFor="answer" className="mt-2 block text-stone-700">{q[2]}</label><textarea id="answer" rows={6} value={answers[q[0]]||''} onChange={e=>setAnswers({...answers,[q[0]]:e.target.value})} className="textarea"/><div className="mt-5 flex flex-wrap gap-3"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(questionIndex-1)} className="secondary"><ArrowLeft className="h-4 w-4"/> Back</button>{questionIndex<questions.length-1?<button disabled={!answers[q[0]]?.trim()} onClick={()=>setQuestionIndex(questionIndex+1)} className="primary-sm">Next CARE question <ArrowRight className="h-4 w-4"/></button>:<button disabled={!answers[q[0]]?.trim()||loading} onClick={getFeedback} className="primary-sm"><Sparkles className="h-4 w-4"/>{loading?'Reviewing…':'Get CARE feedback'}</button>}</div>{error&&<p role="alert" className="mt-4 font-semibold text-red-700">{error}</p>}</>}
    {stage===2&&feedback&&<><Step n="3"/><h2 className="title">Review your CARE feedback</h2><p className="intro">These are formative signals, not grades or a declaration of the correct decision.</p><div className="mt-6 rounded-xl border-l-4 border-[#8b0015] bg-[#f4e9ec] p-5"><h3 className="font-bold text-[#710012]">Overall coaching note</h3><p className="mt-2 text-sm leading-relaxed">{feedback.overallNote}</p></div><div className="mt-6 space-y-4">{feedback.ratings.map(r=><article key={r.criterion} className="rounded-xl border border-stone-200 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{r.criterion}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${r.rating==='Strong'?'bg-emerald-100 text-emerald-800':r.rating==='Developing'?'bg-amber-100 text-amber-900':'bg-rose-100 text-rose-800'}`}>{r.rating}</span></div><p className="mt-3 text-sm"><b>What is working:</b> {r.strength}</p><p className="mt-2 text-sm"><b>Strengthen:</b> {r.improvement}</p></article>)}</div>{feedback.followUpQuestions.length>0&&<div className="mt-6 rounded-xl bg-stone-50 p-5"><h3 className="font-bold">Questions to consider</h3>{feedback.followUpQuestions.map((x,i)=><label key={x} className="mt-4 block text-sm">{x}<textarea rows={3} value={followUps[i]||''} onChange={e=>setFollowUps({...followUps,[i]:e.target.value})} className="textarea"/></label>)}</div>}<Primary onClick={()=>setStage(3)}>Revise or confirm <ArrowRight className="h-4 w-4"/></Primary></>}
    {stage===3&&<><Step n="4"/><h2 className="title">Revise or confirm your reasoning</h2><p className="intro">You may keep your original reasoning. Agreement with the coach is not required.</p><div className="mt-6 space-y-5">{questions.slice(1).map(([key,title,prompt])=><label key={key} className="block"><span className="font-bold">{title}</span><span className="mt-1 block text-sm text-stone-600">{prompt}</span><textarea rows={3} value={revised[key]??answers[key]??''} onChange={e=>setRevised({...revised,[key]:e.target.value})} className="textarea"/></label>)}</div><label className="label">Final professional judgment<textarea rows={4} value={finalJudgment} onChange={e=>setFinalJudgment(e.target.value)} className="textarea"/></label><label className="label">What did you add, reconsider, clarify, or confirm?<textarea rows={3} value={changed} onChange={e=>setChanged(e.target.value)} className="textarea"/></label><Primary disabled={!finalJudgment.trim()||!changed.trim()} onClick={()=>setStage(4)}>Create Practice Record <ArrowRight className="h-4 w-4"/></Primary></>}
    {stage===4&&<><Step n="5"/><h2 className="title">Your Canvas-ready Practice Record</h2><p className="intro">Copy the complete record, open the matching Canvas assignment, paste it into Text Entry, and submit.</p><pre className="mt-6 max-h-[560px] overflow-auto whitespace-pre-wrap rounded-xl bg-[#171717] p-5 text-sm leading-relaxed text-white">{finalRecord}</pre><div className="mt-5 flex flex-wrap gap-3"><button onClick={async()=>{await navigator.clipboard.writeText(finalRecord);setCopied(true)}} className="primary-sm"><Clipboard className="h-4 w-4"/>{copied?'Copied':'Copy Practice Record'}</button><a href={item.canvasUrl} target="_blank" rel="noreferrer" className="secondary text-[#8b0015]">Open Module {item.module} in Canvas <ExternalLink className="h-4 w-4"/></a></div><p className="mt-6 rounded-lg bg-stone-100 p-4 text-sm font-semibold">Your professional judgment remains your own. The CARE Practice Coach helps you notice omissions, test your reasoning, and strengthen safeguards.</p><button onClick={reset} className="mt-5 text-sm font-bold text-[#8b0015] underline">Start a different module</button></>}
   </section><footer className="py-7 text-center text-xs text-stone-500">Use fictional course cases only · No student responses are stored</footer>
  </div>
 </main>
}
function Step({n}:{n:string}){return <p className="eyebrow">STEP {n} OF 5</p>}
function Primary({children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#8b0015] px-5 py-3 font-bold text-white hover:bg-[#6f0011] disabled:cursor-not-allowed disabled:opacity-40">{children}</button>}
