export type CareCase = { module: number; title: string; focus: string; scenario: string; decision: string; canvasUrl: string; priorities: string[] };
const url=(id:number)=>`https://barry.instructure.com/courses/1635156/assignments/${id}`;
export const careCases: CareCase[]=[
{module:1,title:'The Appointment Summary',focus:'Ethical foundations and professional identity',scenario:"A community clinic is testing an AI application that summarizes intake conversations and suggests which clients should receive the earliest appointments. It labels a fictional client's situation as low urgency even though the client describes unstable housing and difficulty obtaining medication. The summary omits those details. A staff member proposes accepting the recommendation because the queue is long and the application appears objective.",decision:'Should the social worker accept the recommendation, override it, or pause for human review?',canvasUrl:url(7461672),priorities:['omitted high-stakes context','human triage authority','delayed-care harm','client voice and source verification']},
{module:2,title:'The Mobile Only Renewal',focus:'Access, usability, and technology fit',scenario:'A community agency moves benefits renewal to a mobile-only application. Jordan has an older phone, intermittent data, limited storage, and little confidence with online forms. Jordan prefers face-to-face help. Missing the deadline could interrupt food and housing assistance, but staff time for in-person support has been reduced.',decision:'Should the agency proceed, pause, or operate the app alongside accessible alternatives?',canvasUrl:url(7461673),priorities:['device and connectivity barriers','client choice','benefit-loss risk','accessible alternatives']},
{module:3,title:'The Benefits Navigator',focus:'Policy, power, and responsible app decisions',scenario:'An agency wants an AI-assisted app that screens families for public benefits. It stores household information, gives staff a risk score, and automatically closes an intake when it predicts a family is unlikely to qualify. Clients may request staff review, but that option is difficult to find.',decision:'What governance conditions are needed before a pilot, and should automatic intake closure be permitted?',canvasUrl:url(7461662),priorities:['benefit rules and sensitive data','visible appeal and override','wrongful closure','affected-family participation']},
{module:4,title:'The Harbor House Pilot',focus:'Technology fit, testing, and responsible integration',scenario:'Harbor House built a no-code scheduling and reminder app. It copies contact information into a shared spreadsheet, sends reminders only in English, and assumes reliable smartphones and data. Staff want to use it with all new clients next week. No one has tested wrong numbers, shared devices, language access, failed messages, or a return to the prior workflow.',decision:'Should Harbor House proceed, pause, or run a smaller pilot?',canvasUrl:url(7461663),priorities:['real-world fit','data and change control','disclosure and missed-service harm','limited reversible testing']},
{module:5,title:'The Community Connection Account',focus:'Digital communication, boundaries, and professional presence',scenario:'An agency asks Maya, an MSW intern, to manage a social-media account. A client sends Maya a personal follow request and later messages the agency account about a crisis. Several staff share the account, response expectations are unclear, and no one has decided what may be discussed in direct messages.',decision:'Should the agency launch now, pause, or begin with a tightly limited pilot?',canvasUrl:url(7461674),priorities:['intern role and boundaries','shared-account authority','confidentiality and crisis risk','clear limits and escalation']},
{module:6,title:'The Intake Shortcut',focus:'Privacy, security, and data stewardship',scenario:"A team proposes a free transcription and summarization app during intake. Its storage, retention, access controls, deletion, and training-data practices are unclear. Staff have not obtained informed consent, completed a privacy review, or prepared a safe manual fallback.",decision:'Should the team proceed, pause, or test without client information?',canvasUrl:url(7461675),priorities:['sensitive intake content','vendor control','irreversible exposure','synthetic testing and fallback']},
{module:7,title:'The Engagement Drop Off',focus:'Client engagement and service delivery',scenario:"A check-in app improves response rates for some clients but excludes people with limited data, shared phones, disabilities, language barriers, or safety concerns. Missed check-ins may be interpreted as disengagement and may affect continued services.",decision:'Should the agency expand, pause, or run a smaller test while preserving other pathways?',canvasUrl:url(7461676),priorities:['access and safety','human interpretation of nonresponse','service-loss harm','equal alternatives']},
{module:8,title:'The Advocacy Dashboard',focus:'Technology for advocacy and policy change',scenario:'A coalition wants to publish a dashboard and AI-generated campaign messages using neighborhood-level service data. Community members have not reviewed the framing, small groups may be identifiable, and graphics may imply unsupported conclusions.',decision:'Should the coalition publish, pause, or begin with a smaller community-reviewed release?',canvasUrl:url(7461677),priorities:['data limitations and stigma','community authority','re-identification','community review and correction']},
{module:9,title:'The Immersive Pilot',focus:'Immersive technology and responsible innovation',scenario:'A program proposes a required VR trauma-informed training simulation. Some users report motion sickness and distress, accessibility is uneven, and the team has not defined consent, stopping rules, facilitator responsibilities, or a non-immersive alternative.',decision:'Should the program require it, pause, or conduct an optional limited pilot?',canvasUrl:url(7461678),priorities:['trauma and accessibility','voluntary participation','persistent distress','equivalent alternative']},
{module:10,title:'The Virtual Clinic Queue',focus:'Telehealth and the virtual practice environment',scenario:'A virtual clinic introduces automated triage and video visits. Connectivity, home privacy, language, emergency location, disability access, and escalation vary. The system moves clients with incomplete forms to the end of the queue and treats a dropped visit as voluntary departure.',decision:'Should the clinic implement, pause, or conduct a limited pilot with parallel access routes?',canvasUrl:url(7461679),priorities:['clinical and access context','triage authority','missed-emergency harm','parallel routes']},
{module:11,title:'The Resource Ranking Tool',focus:'Technology, equity, and social justice',scenario:'An agency uses an algorithm to rank applicants for limited support. Historical data may reproduce inequity, the score is difficult to explain, and clients have no visible appeal path. Staff must follow the ranking unless a supervisor approves an exception.',decision:'Should the agency continue, pause, or restrict it to a monitored advisory role?',canvasUrl:url(7461680),priorities:['structural inequity','vendor opacity and override','discriminatory allocation','transparent appeal']},
{module:12,title:'The Next Generation Service Lab',focus:'Future readiness and responsible innovation',scenario:'A team proposes combining generative AI, predictive analytics, and automated outreach. Evidence is early, and responsibility for monitoring, correction, client notice, vendor changes, and withdrawal is unclear. Leaders want a rapid launch so the organization appears innovative.',decision:'Should the organization launch, pause, or create a staged and reversible learning pilot?',canvasUrl:url(7461681),priorities:['evidence and capacity','lifecycle authority','compounded errors','staged testing and withdrawal']},
];
export const careCaseByModule=(m:number)=>careCases.find(c=>c.module===m);
